name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write # Needed for creating releases

    steps:
      - uses: actions/checkout@v4 # Updated to v4
        with:
          submodules: recursive
          fetch-depth: 0 # Needed for correct build numbering

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable" # Use latest stable instead of specific version

      - name: Set Build Number
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "Building version: ${GITHUB_REF#refs/tags/v}, build: $(git rev-list --count HEAD)"

      - name: Build App
        run: |
          # Print Xcode version for debugging
          xcodebuild -version

          # List available schemes
          xcodebuild -project clip-board-app.xcodeproj -list

          # Build without modifying plist settings (let Xcode choose appropriate settings)
          xcodebuild -project clip-board-app.xcodeproj \
            -scheme "clip-board-app" \
            -configuration Release \
            -derivedDataPath build \
            -archivePath build/clip-board-app.xcarchive \
            archive

          # Verify the build output
          ls -la build/clip-board-app.xcarchive/Products/Applications/

          # Create app bundle
          cd build/clip-board-app.xcarchive/Products/Applications/
          zip -r ../../../../ClipMaster-Pro.zip "clip-board-app.app"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1 # Updated to modern release action
        with:
          name: ClipMaster Pro ${{ env.VERSION }}
          body: |
            ClipMaster Pro Release ${{ env.VERSION }}
            Build Number: ${{ env.BUILD_NUMBER }}

            ## What's Changed
            * Auto-generated release for version ${{ env.VERSION }}

            ## Installation
            1. Download the zip file
            2. Extract the app
            3. Move to Applications folder
            4. Double click to run
          draft: false
          prerelease: false
          files: ./ClipMaster-Pro.zip
